[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
zconnect = "EnELF8Dv1i1Lr6JQYt8UyRJqfR32PJoCeCBNdtijhWXv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
