[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
zkonnect = "DJKkDHARbjNUe2WucgNkwY2dJEFtkMh9urf8dB62cSuP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
